### ISSUE TITLE
Feature Request: Share Settings (at least Turn Duration & Mob Order) via URL for code dojos

### ISSUE THREAD

**Issue by nickdelgrosso** [mrozbarry/mobtime#134]
Hi,

Loving mobtime!  For my code dojo events, I'd like to be able to share a link with the participants that has the timer pre-configured, as we have multiple mobs running simultaneously.  Managing large groups is sometimes a challenge, especially when one has to give a lot of instructions, and so these little features can make a big difference in giving the participants a smooth experience and minimize the number of steps until they are doing their kata.  I'd like to add some new roles to the mob as part of the rotation, and being able to give them a pre-configured timer would help.  

This seems like a small enough amount of info that it could even go in the url  (e.g. mobti.me/?time=5&roles=navigator+driver). 

The workflow I'm imagining would be something like:
  1. Event organizer changes settings in a timer app, then clicks something like "Share Settings URL" from the settings menu.
  2. Organizer pastes settings into chat window / posts link in presentation for groups to copy into their own browsers.
  3. The rest as normal:
    a. The URL goes to the "Get Started" page of the app, where they choose their name.  They click "Get Started".
    b. The timer appears as with the settings filled in.  The mob can still customize everything (names, goals, etc), but those changes only affect their own timer session.  

If you're interested, with help, I'd be interested in collaborating on this feature.

Best wishes,

Nick

**Comment by nickdelgrosso** [comment]
Just realized this is a duplicate of issue #104 .

**Comment by mrozbarry** [comment]
Yup, closing, feel free to follow the conversation over on the other ticket.
