### ISSUE TITLE
Allow to click circles of checkmarks, not only text

### ISSUE THREAD

**Issue by dbartholomae** [mrozbarry/mobtime#137]
Hi everyone!

A small usability idea: Currently when enabling options (e. g. Client Settings/Enable timer sounds) clicking the circle left of the option does not enable it, only clicking the text does.
I'm happy to provide a PR.

Best,
Daniel

**Comment by mrozbarry** [comment]
If you have the time and the general idea of what needs to be updated, I'd gladly accept a PR. Otherwise I will get to this shortly, recently some people on my team also mentioned it, and since then, it has been a vague irritation :laughing: .
