### ISSUE TITLE
Users were removed automatically

### ISSUE THREAD

**Issue by ajoelp** [mrozbarry/mobtime#142]
Summary:
- Had a mob of 12 people
- Turn ended (Timer was at 0) and the next driver had left.
- Removed the next driver
- Everybody except the top 4 people were removed from the list.

**Comment by mrozbarry** [comment]
Wrote a test to simulate this case, and I wasn't able to reproduce it, so I'm guessing a bunch of people tried to edit the mob list at the same time and as a result, accidentally removed a bunch of people. Let me know if you can reproduce this again, and I'll be happy to re-open and try to reproduce it more specifically in a test.
