### ISSUE TITLE
Unable to request Notification Permission

### ISSUE THREAD

**Issue by vehikl-aganoa** [mrozbarry/mobtime#146]
This seems busted

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/71042258/95344184-5c796980-0887-11eb-8658-7e0f448f95c9.png">

**Comment by mrozbarry** [comment]
@vehikl-aganoa what browser/version?

**Comment by vehikl-aganoa** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/71042258/95344454-ac583080-0887-11eb-8c1a-b126c776746d.png">

**Comment by vehikl-aganoa** [comment]
ETA ON FIX?!

**Comment by mrozbarry** [comment]
@vehikl-aganoa it's going to be sometime today, when I have roughly a full hour free. Sorry for the inconvenience

**Comment by vehikl-aganoa** [comment]
WHEN DONE

**Comment by mrozbarry** [comment]
This is live in https://dev.mobti.me/ , and will make its way into production soon.
