### ISSUE TITLE
Refine design

### ISSUE THREAD

**Issue by mrozbarry** [mrozbarry/mobtime#32]
I'm not a designer, and this could look way better. I'm currently working with @frankyfrankfrank on some design ideas, but others are welcome, too.

**Comment by FrankyFrankFrank** [comment]
https://xd.adobe.com/view/08ed8484-6843-48df-50a6-d4ab0f76e6a8-7edc/#access_token=eyJ4NXUiOiJpbXNfbmExLWtleS0xLmNlciIsImFsZyI6IlJTMjU2In0.eyJpZCI6IjE1ODUwMjA5NTI1NzZfNjdhMGYyZDQtNDYxMS00MWIyLWJkYzAtNTNlNTI0MjQzNjc3X3VlMSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiJBMEE1NEY3NzUyMTY0QzI0MEE0OTBENERAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJmZyI6IlVKTEFWUUY1VkxPNTZINktLNllMUVBRQUFFPT09PT09Iiwic2lkIjoiMTU4NTAyMDk1MjU3Nl81MmYyMjU0MS04YmUyLTQ5MDMtOGNhZC0zOGNkODZlNTExZmNfdWUxIiwibW9pIjoiZTBlNmM5YTUiLCJjIjoiUENkUThyQWRzMUlsWHVVeXJGUWkrdz09IiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTU4NTAyMDk1MjU3NiJ9.Mut6KyDqR14E4n4s-fKdDGp96ZcYppl7pAw9yGfP8sBSZmPmpzc3-QkyiXHpgI-CiXZlpoue0q38yqGt2vHNKuYd6b0HHTUJ66PA4AXrlvPsn_VZwb8Q5hxAdIROaM_FxasPhQDIlxGutr_y5JCeVR-KsOdu0kRUGNb1Yqhgvfb_S2UrDL9niaE_NruMh8ogGDCuRdbY2vmZhs5qt_jUjRYlUz6vKFmc6smYeM2DD0y0y3G92qQoBHXQcbE9Skapw0B57FUsztA9FzfvHryd2CfB-jN-jIfhW2XgFJ6MYiLDYnKzXAKD1i8fK4mD7Lf5hq3itajtGk_xlIqklB6J2Q&token_type=bearer&expires_in=86399992

**Comment by FrankyFrankFrank** [comment]
![image](https://user-images.githubusercontent.com/6907518/77450210-5a5b2c00-6dc9-11ea-9049-8be21ccc7bd5.png)
