### ISSUE TITLE
API

### ISSUE THREAD

**Issue by simonharrer** [mrozbarry/mobtime#36]
We've developed 'mob', a CLI tool that allows to handover your state via git more easily. You can start a session by `$ mob start 10` which will get the previous state and starts a 10 minute timer. Problem often is: the timer is overheard. But rotating often is important. 

To solve this, I was thinking how to combine 'mob' with 'mobtime'. 

The idea: 'mob' could send the name of the user, the duration (10 minutes), the timestamp, and maybe a hash of the origin url as a mob name when `$ mob start 10` is called and others could then open 'mobtime' as well in the browser to help keep track of rotation. With that approach, we wouldn't really want to enter data into 'mobtime' manually, but it's only fed from the 'mob' tool calls - making the ui components of 'mobtime' for this case unecessary.

**Comment by mrozbarry** [comment]
@simonharrer does your mob setup care much about positions like navigator or driver, and is there a rotation? You can certainly not add people to the mob section and just use the timer.

So this is how the internals work, and you might be able to hack something together for now:

1. Connect a websocket to `https://mobtime.mrbarry.com/your-timer-id`
2. It will send a payload that looks something like `{ type: 'token', token: 'YOUR SESSION TOKEN', state: { ...stateOfTimer } }` - take that token
3. Every minute or so, send a `{ ping: <unix timestamp in milliseconds> }` through the websocket to keep the socket connection alive.
4. Now you can make API calls via `https://mobtime.mrbarry.com/api/X` with `Authorize: token <token from websocket>` as a header.

The API you're going to care about is:

`/api/timer/start/<milliseconds>` - I typically add `999` so the initial second runs without making the timer bump to the next second
`/api/timer/pause`
`/api/timer/resume`

And if you care about mob person management:

`/api/mob/add/<encoded name of mobber>`
`/api/mob/remove/<encoded name of mobber>`
`/api/mob/cycle` to rotate mobber positions if you have a regular/predictable rotation.

But keep in mind that this is sort of shoe-horning how mobtime works. You might find just having a dedicated person in charge of managing the timer to be just as effective without having to introduce new code.

---

I also opened #35 which an _alternative_ path forward, but I need to think through a lot of implications, and it may require a number of prerequesite features that I may not want.

**Comment by mrozbarry** [comment]
@simonharrer does that initial plan work? I can better document the API if that will help. It looks like go has [a websocket library](https://github.com/gorilla/websocket) - you could temporarily connect a websocket, do a series of api calls with the token, then disconnect to do what you want. There's no current penalties for quick websockets or connections over time.

**Comment by simonharrer** [comment]
Just to let you know that I've currently so much on my plate that I don't know when I can come back to this. Closing this for now, and will reopen when I do have time for this. Thanks for your awesome and quick help already!
