### ISSUE TITLE
Set custom sound for notification when timer is up

### ISSUE THREAD

**Issue by mrozbarry** [mrozbarry/mobtime#64]

**Comment by mrozbarry** [comment]
Will solve #90

**Comment by mrozbarry** [comment]
Some timer complete sound effects I'm thinking about

 - https://bigsoundbank.com/detail-1828-pneumatic-horn-simple-2.html
 - https://bigsoundbank.com/detail-0477-wilhelm-scream.html
 - https://bigsoundbank.com/detail-0283-song-of-rooster.html

Any other suggestions? My only requirement is they need to be royalty free, and preferably available in mp3 (but I can convert them as long as it doesn't violate any licensing).

**Comment by rzijp** [comment]
All great suggestions, what about letting the user choose?

**Comment by mrozbarry** [comment]
> what about letting the user choose

Just to go down this rabbit hole, here's the cascade of questions I have

 - dropdown/radio group from pre-selected group
   - Just add audio files to public directory, and give the user a list to pick from
 - user can pick an audio file
   - Custom URL
     - Give the user a text field to set audio, and do initial test to be sure the url works
   - Local file
     - User has to pick file each page reload
       - Audio is local, no licensing issue
     - User has to upload file somewhere, which goes back to custom url
       - Any problems with licensing?
     - Client needs to serialize audio file into some form of local storage
       - Audio is local, no licensing issue
