### ISSUE TITLE
Allow users to edit existing goals and names

### ISSUE THREAD

**Issue by FRFlor** [mrozbarry/mobtime#89]
Right now, if we want to edit a goal, we have to delete it and retype it. 

It would be a nice quality of life change to be able to edit it.

**Comment by mrozbarry** [comment]
Agreed, I'll work on how this will work with drag and drop.

**Comment by FRFlor** [comment]
I've noticed that click/double click event handlers seem to work pretty well even if you're handling drag and drop. 

Maybe if we double-click on the item, it becomes editable.

**Comment by mrozbarry** [comment]
Maybe, but double-clicking wouldn't necessarily be obvious without instructions, and instructions are a huge sign of bad UI and UX.

Probably an edit icon would be good enough, or maybe dotted underline and click on the text. I'll tinker with it.

**Comment by FRFlor** [comment]
> Maybe, but double-clicking wouldn't necessarily be obvious without instructions, and instructions are a huge sign of bad UI and UX.

Good point! Yeah, an edit icon would be neat
