### ISSUE TITLE
Notification does not always make a noise

### ISSUE THREAD

**Issue by mrozbarry** [mrozbarry/mobtime#90]

**Comment by alterisian** [comment]
I have experienced this. Chrome on ubuntu. Maybe just not hearing a one off beep? Unsure. Perhaps one every 2 seconds for 10 seconds?

**Comment by mrozbarry** [comment]
There _might_ be a security feature in the browser that requires a user to interact with the page before it can make notification noises, but I can't been able to fully verify this yet.

**Comment by mrozbarry** [comment]
Closing this issue, thread will continue into #64
