### ISSUE TITLE
Allow users to change between rules "driver becomes navigator" and "navigator becomes driver" 

### ISSUE THREAD

**Issue by dpolivaev** [mrozbarry/mobtime#95]
Personally, I prefer "navigator becomes driver" and not the other way round, because it is easier to stop thinking after you have been forced to think and to lead. I also find the other transition - stop thinking as a driver and then  give your 100% - very hard to accomplish.

Some other people have different opinion, so it could be a useful setting.

**Comment by stefanscheidt** [comment]
"+1" on this.

**Comment by mrozbarry** [comment]
My plan is to have this up by next week. Thanks for the suggestion!

**Comment by mrozbarry** [comment]
This should be live on https://dev.mobti.me - let me know if this works they way you expect, or if you have any feedback on how it can be improved

**Comment by dpolivaev** [comment]
I am sorry, I have not found how to change the "on rotation the driver becomes navigator" rule by the opposite on dev.mobti.me

**Comment by mrozbarry** [comment]
Oh, you're right, I forgot to rebase before my deploy - give it another refresh, and you should be good to go!

**Comment by dpolivaev** [comment]
Thank you very much. It looks better than I expected because you made it very flexible.
Actually I learned from Llewellyn Falco that he suggests using words "typing" for the driver, "talking" for navigator, and "next" to indicate who is the next navigator. And with your solution, I can implement it easily.

I would use a smaller font size for the field where the roles are edited.

I also have some unrelated questions, so I would like to open separate issues for them.

**Comment by mrozbarry** [comment]
The issue board is open, make as many as you need.

**Comment by dpolivaev** [comment]
I found that your current solution handles a list of 3 but does not handle a list of 1.
Actually, there are mob versions with no navigator, just the driver and the mob.
Do you think you could support lists of one element?

**Comment by mrozbarry** [comment]
@dpolivaev A fix has been pushed. Honestly, I hadn't considered that some mobs only have a driver.

**Comment by dpolivaev** [comment]
By the way, I would change the wording from "One or more comma separated list of positions" to "One or more comma-separated positions" or "One or more comma-separated roles"
